<?php

namespace Andre\Thelittlefoxesclub\ContactBundle\Repository;

/**
 * AuthpersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthpersonRepository extends \Doctrine\ORM\EntityRepository
{
}
