<?php

namespace Andre\Thelittlefoxesclub\ContactBundle\Repository;

/**
 * MasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterRepository extends \Doctrine\ORM\EntityRepository
{
}
