<?php

namespace Andre\Thelittlefoxesclub\ContactBundle\Repository;

/**
 * WeeklyjchildrenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeeklyjchildrenRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByCustomerId()
    {
    	
        $queryBuilder = $this->createQueryBuilder('crp')
                            ->select("crp.id,c.name")
                            ->join("crp.accountId","c")
                            ->where('crp.weeklyId = :contactId')
                            
                            ;
            
            
            
 
        return $queryBuilder;
    }
}
