<?php

namespace Andre\Thelittlefoxesclub\ContactBundle\Repository;
use Andre\Thelittlefoxesclub\ContactBundle\Entity\Weekly;
/**
 * WeeklyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeeklyRepository extends \Doctrine\ORM\EntityRepository
{
	function getNumberofWeeks(Weekly $a)
	{
		return $a->getName();
	}
	
}
